operation :
    save : False
    log_dir : palladium-smf
    device : cuda:7
environment :
    benchmark : dmc
    domain_name : hopper
    task_name : stand
    seed : 0
    visualize_reward : False
    from_pixels : True
    image_size : 64
    timestep_stride : 6
    timestep_max : 7668
    add_screen_count : 1

parameters :

    edges_dataset :
        data_root : SMF_screenshots_enriched/screenshots
        zero_screenshot_path : Sadistic_Music_Factory_screenshots/Sadistic_Music_Factory/Zero_screenshot.png
        zero_screenshot_part_path : Sadistic_Music_Factory_screenshots/Sadistic_Music_Factory/Zero_screenshot_part.png
        zero_screenshot_player_x : 75
        zero_screenshot_player_y : 546
        pad : 32
        aperture_size : 5 
        part_size : 100
        
        
    dreamer :
        train_iterations : 10000
        horizon_length : 15
        batch_size : 50
        batch_length : 15
        collect_interval : 100
        num_interaction_episodes : 1
        seed_episodes : 5
        num_evaluate : 3
        
        kl_divergence_scale : 0.01
        free_nats : 3
        discount : 0.99
        lambda_ : 0.95
        
        use_continue_flag : False
        actor_learning_rate : 0.00008
        critic_learning_rate : 0.00008
        model_learning_rate : 0.0006
        grad_norm_type : 2
        clip_grad : 100
        
        deterministic_size : 200
        stochastic_size : 70
        embedded_state_size : 1024
        buffer :
            capacity : 50000
        
        vae : 
            in_channels : 1
            num_hiddens : 64
            embedding_dim : 64
            embedding_image_size : 4
            true_percentage_full : 0.1
            true_percentage_part : 0.1
            activation : LeakyReLU

        rssm :
            recurrent_model : 
                hidden_size : 200
                activation : ELU

            transition_model : 
                hidden_size : 200
                num_layers : 2
                activation : ELU
                min_std : 0.1

            representation_model:
                hidden_size : 200
                num_layers : 2
                activation : ELU
                min_std : 0.1
            
        reward :
            hidden_size : 400
            num_layers : 2
            activation : ELU

        continue_ :
            hidden_size : 400
            num_layers : 3
            activation : ELU
        
        agent :
            actor :
                hidden_size : 400
                min_std : 0.0001
                init_std : 5.
                mean_scale : 5
                activation : ELU
                num_layers : 2

            critic : 
                hidden_size : 400
                activation : ELU
                num_layers : 3 